spring.application.name=msvc-items
server.port=8002
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
config.base.enbdpoint.msvc-products=http://msvc-products

# Micrometer Tracing configuration
management.tracing.sampling.probability=1.0
spring.reactor.context-propagation=AUTO
management.tracing.enabled=true
management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans