spring.application.name=msvc-items
server.port=8002
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
config.base.enbdpoint.msvc-products=http://msvc-products

# Micrometer Tracing configuration
management.tracing.sampling.probability=1.0
spring.reactor.context-propagation=AUTO
management.tracing.enabled=true