spring.application.name=msvc-items
server.port=8005
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://eureka-server:8761/eureka}
config.base.enbdpoint.msvc-products=http://msvc-products

# Micrometer Tracing configuration
# management.tracing.sampling.probability=1.0
# spring.reactor.context-propagation=AUTO
# management.tracing.enabled=true
# management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans